name: Update README â­
on:
  schedule:
    - cron: "51 */4 * * *"  # Every 4 hours
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: k2bd/advent-readme-stars@v1
        with:
          userId: 2441037
          leaderboardId: 2441037
          sessionCookie: ${{ secrets.AOC_SESSION }}
          starSymbol: ğŸ„
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update README stars
